export enum validSpecialties {
  recruitment = 'reclutamiento y selección de talento tecnológico',
  talentmanagement = 'gestión del talento',
  performancemanagement = 'gestión del desempeño',
  trainingdevelopment = 'capacitación y desarrollo',
  organizationalculture = 'cultura organizacional y clima laboral',
  changemanagement = 'gestión del cambio',
  compensationbenefits = 'compensación y beneficios',
  conflictmanagement = 'gestión de conflictos',
  developer = 'desarrollador',
  designer = 'diseñador',
  dataanalyst = 'analista de datos',
  cybersecurity = 'especialista en seguridad informática',
  systemsengineer = 'ingeniero de sistemas',
  databaseadministrator = 'administrador de bases de datos',
  softwareprojectmanager = 'gerente de proyectos de software',
  softwarequality = 'especialista en calidad de software',
  softwarearchitect = 'arquitecto de software',
  uxspecialist = 'especialista en experiencia de usuario (ux)',
  uispecialist = 'especialista en experiencia de usuario (ui)',
  networkengineer = 'ingeniero de redes y sistemas',
  systemsintegration = 'especialista en integración de sistemas',
  ai_ml_specialist = 'especialista en inteligencia artificial y aprendizaje automático',
  mobiledeveloper = 'especialista en desarrollo móvil',
  webdeveloper = 'especialista en desarrollo web',
  devopsspecialist = 'especialista en devops',
  testingqa = 'especialista en testing y qa (control de calidad)',
}
