export enum validSpecialties {
  Recruitment = 'Reclutamiento y selección de talento tecnológico',
  TalentManagement = 'Gestión del talento',
  PerformanceManagement = 'Gestión del desempeño',
  TrainingDevelopment = 'Capacitación y desarrollo',
  OrganizationalCulture = 'Cultura organizacional y clima laboral',
  ChangeManagement = 'Gestión del cambio',
  CompensationBenefits = 'Compensación y beneficios',
  ConflictManagement = 'Gestión de conflictos',
  Developer = 'Desarrollador',
  Designer = 'Diseñador',
  DataAnalyst = 'Analista de datos',
  CyberSecurity = 'Especialista en seguridad informática',
  SystemsEngineer = 'Ingeniero de sistemas',
  DatabaseAdministrator = 'Administrador de bases de datos',
  SoftwareProjectManager = 'Gerente de proyectos de software',
  SoftwareQuality = 'Especialista en calidad de software',
  SoftwareArchitect = 'Arquitecto de software',
  UXSpecialist = 'Especialista en experiencia de usuario (UX)',
  UISpecialist = 'Especialista en experiencia de usuario (UI)',
  NetworkEngineer = 'Ingeniero de redes y sistemas',
  SystemsIntegration = 'Especialista en integración de sistemas',
  AI_ML_Specialist = 'Especialista en inteligencia artificial y aprendizaje automático',
  MobileDeveloper = 'Especialista en desarrollo móvil',
  WebDeveloper = 'Especialista en desarrollo web',
  DevOpsSpecialist = 'Especialista en DevOps',
  TestingQA = 'Especialista en testing y QA (Control de calidad)',
}
